#!/usr/bin/env bash

# Update and upgrade the system
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Define the custom header configuration
custom_header_config="add_header X-Served-By \$03-web-02;"

# Add the custom header configuration to Nginx default site configuration
sudo sed -i "/server_name _;/a $custom_header_config" /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo systemctl reload nginx

# Display installation completion message
echo "Nginx configured with custom header. Custom header name: X-Served-By, Value: 03-web-02."
