#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup  # Backup existing configuration
sudo bash -c 'cat <<EOL > /etc/haproxy/haproxy.cfg
frontend web
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    mode http
    balance roundrobin
    server web-01 335656-web-01-web-01:80 check
    server web-02 335656-web-02-web-02:80 check
EOL'

# Restart HAProxy
sudo service haproxy restart

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy
