#!/usr/bin/env bash

# Use 'ifconfig' to get network interface information and extract IPv4 addresses
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*)' | awk '{print $2}' | sed 's/addr://'
